name: 'Docker Image Build, Test, Scan, and Publish'

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo "${{ github.action_path }}" && ls -ltr "${{ github.action_path }}"
    - name: Sleep
      shell: bash
      run: bash ${{ github.action_path }}/b.sh
    - name: Show action commit
      run: |
         cd "$GITHUB_ACTION_PATH"
         git rev-parse HEAD
         git show -s --pretty=%D HEAD