name: 'Docker Image Build, Test, Scan, and Publish'

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo "${{ github.action_path }}"
        ls -ltr "${{ github.action_path }}"
        cd "${{ github.action_path }}"
        pwd
        cat "${{ github.action_path }}"/../common.properties
    - name: Debug
      uses: /home/runner/work/_actions/nmanojorg/RootRepo/test2/.github/actions/validate-inputs