name: Validate Inputs
description: Validates GitHub Action inputs with required checks, type checks, file existence, and range validations.



runs:
  using: "composite"
  steps:
    - name: Run validation script
      shell: bash
      run: |
        echo "Running validate-input script"
        env
