on:
  workflow_call:
    secrets:
      GENERIC_YAML_SECRET:
        required: true

env:
  b: 1

jobs:
  set-secrets-env:
    env:
      c: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "nmanojorg/RootRepo"
          ref: main
          path: 'cicd-shared-lib'
        
      - shell: bash
        run: printenv

      - uses:  ./cicd-shared-lib/.github/actions/docker-ci

