name: Simple Reusable Workflow

on:
  workflow_call:
    secrets:
      GENERIC_JSON_SECRET:
        required: false

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check if TEST is set
        run: |
          env
          pwd
          ls -ltr
          echo "${{ github.workflow }}"
          echo "${{ github.workflow_ref }}"
      - name: Import secrets as env vars
        shell: bash
        run: |
          json="${{ secrets.GENERIC_JSON_SECRET }}"
          echo $json
          if [ -n "$json" ]; then
            if echo "$json" | jq empty; then
              jq -r 'to_entries[] | "\(.key)=\(.value)"' <<< "$json" | while IFS= read -r line; do
                value="${line#*=}"
                echo "::add-mask::$value"
                echo "$line" >> $GITHUB_ENV
              done
            else
              echo "GENERIC_JSON_SECRET is not valid JSON"
            fi
          else
            echo "GENERIC_JSON_SECRET is empty or not set"
          fi
      - name: debug
        shell: bash
        run: |
          echo "${{ env.secret_1 }}"
          echo "${{ env.secret_2 }}"
