name: Conditional Job Workflow

on:
  push:
  workflow_call:
    inputs:
      runJob1:
        type: boolean
        required: true
      runJob3:
        type: boolean
        required: true
      runJob4:
        type: boolean
        required: true

jobs:
  job1:
    if: ${{ inputs.runJob1 }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 1"

  job2:
    name: Always Run Job 2
    needs: [job1]
    if: ${{ inputs.runJob1 && success() || !inputs.runJob1 }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 2"

  job3:
    if: ${{ inputs.runJob3 && needs.job2.result == 'success' }}
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 3"

  job4:
    if: ${{ inputs.runJob4 && needs.job2.result == 'success' }}
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 4"

  job5:
    name: Final Job (Only if all dependencies succeeded)
    if: >-
      ${{
        needs.job2.result == 'success' &&
        (!inputs.runJob3 || needs.job3.result == 'success') &&
        (!inputs.runJob4 || needs.job4.result == 'success')
      }}
    needs:
      - job2
      - job3
      - job4
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 5"
