name: Simple Reusable Workflow

on:
  workflow_call:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check if TEST is set
        run: |
             if [[ -n "$TEST" ]]; then
                echo "TEST variable is set"
             else
                echo "TEST variable is NOT set"
             fi
