name: Simple Reusable Workflow


on:
  workflow_call:
    secrets:
      GENERIC_JSON_SECRET:
        required: false

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check if TEST is set
        run: |
             env
             pwd
             ls -ltr
             echo "${{ github.workflow }}"
             echo "${{ github.workflow_ref }}"
      - name: Import secrets as env vars
        shell: bash
        run: |
          json='${{ secrets.GENERIC_JSON_SECRET }}'
          if [ "$json" != "" ]; then
            echo "$json" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          fi
      - name: debug
        shell: bash
        run:  echo "${{ env.secret_1 }}"; echo "${{ env.secret_2 }}"
