name: Simple Reusable Workflow

on:
  workflow_call:
    secrets:
      GENERIC_YAML_SECRET:
        required: false

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Import secrets as env vars (YAML)
        shell: bash
        run: |
          yaml="${{ secrets.GENERIC_YAML_SECRET }}"
          echo "$yaml"
          if [ -n "$yaml" ]; then
            echo "$yaml" > temp.yaml
            yq eval 'to_entries | .[] | "\(.key)=\(.value)"' temp.yaml | while IFS= read -r line; do
              value="${line#*=}"
              echo "::add-mask::$value"
              echo "$line" >> $GITHUB_ENV
            done
          else
            echo "GENERIC_YAML_SECRET is empty or not set"
          fi

      - name: debug
        shell: bash
        run: |
          echo "${{ env.secret_1 }}"
          echo "${{ env.secret_2 }}"
