on:
  workflow_call:
    secrets:
      GENERIC_YAML_SECRET:
        required: true

jobs:
  set-secrets-env:
    runs-on: ubuntu-latest
    steps:
      - name: Parse GENERIC_YAML_SECRET and set as env vars
        run: |
          echo "${{ secrets.GENERIC_YAML_SECRET }}" > secrets.yaml
          while IFS=": " read -r key value; do
            if [[ "$key" =~ ^[a-zA-Z0-9_]+$ ]] && [ -n "$value" ]; then
              key_upper=$(echo "$key" | tr '[:lower:]' '[:upper:]')
              echo "Setting $key_upper as env var"
              echo "::add-mask::$value"
              echo "$key_upper=$value" >> $GITHUB_ENV
            fi
          done < <(grep -E '^[^ ]+:' secrets.yaml)
      - name: Show set environment variables
        run: |
          echo "SECRET_1: $SECRET_1"
          echo "SECRET_2: $SECRET_2"
