name: Conditional Job Workflow

on:
  push:

jobs:
  job1:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "? Running Job 1"

  job2:
    name: Always Run Job 2
    needs: [job1]
    if: always() && (needs.job1.result == 'success' || needs.job1.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(needs) }}'

  job3:
    name: Conditional Job 3
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "? Running Job 3"
