on:
  workflow_call:
    secrets:
      GENERIC_YAML_SECRET:
        required: true

env:
  b: 1

jobs:
  set-secrets-env:
    env:
      c: 1
    runs-on: ubuntu-latest
    steps:
       - shell: bash
         run: printenv

       - shell: bash
         run: | 
              ls -ltr "${{ github.env }}"
              cat "${{ github.env }}"
              printenv | grep "a="
              printenv | grep "b="
              printenv | grep "c="

