name: Conditional Job Workflow

on:
  push:
  workflow_call:
    inputs:
      runJob1:
        type: boolean
        required: true
      runJob3:
        type: boolean
        required: true
      runJob4:
        type: boolean
        required: true

jobs:
  job1:
    if: ${{ inputs.runJob1 }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "? Running Job 1"

  job2:
    name: Always Run Job 2
    needs: [job1]
    if: always()
    runs-on: ubuntu-latest
    outputs:
      status: success
    steps:
      - run: "echo ${{ toJSON(needs) }}"

  job3:
    name: Conditional Job 3
    if: ${{ inputs.runJob3 }}
    needs: [job2]
    runs-on: ubuntu-latest
    outputs:
      status: success
    steps:
      - run: echo "? Running Job 3"

  job4:
    name: Conditional Job 4
    if: ${{ inputs.runJob4 }}
    needs: [job2]
    runs-on: ubuntu-latest
    outputs:
      status: success
    steps:
      - run: echo "? Running Job 4"

  job5:
    name: Final Job (Runs Only if Conditions Pass)
    needs: [job2, job3, job4]
    runs-on: ubuntu-latest
    steps:
      - run: echo "?? Running Final Job 5"
