name: Simple Reusable Workflow

on:
  workflow_call:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check if TEST is set
        run: |
             env
             pwd
             ls -ltr
             echo "${{ github.workflow }}"
             echo "${{ github.workflow_ref }}"
