name: Conditional Job Workflow

on:
  push:
  workflow_call:
    inputs:
      runJob1:
        type: boolean
        required: true
      runJob3:
        type: boolean
        required: true
      runJob4:
        type: boolean
        required: true
jobs:
  job1:
    name: Always Run Job 2
    runs-on: ubuntu-latest
    steps:
      - run: | 
             echo "Running Job 2"
             echo "$REPO_NAME"

  
