name: Simple Reusable Workflow

on:
  workflow_call:
    secrets:
      GENERIC_YAML_SECRET:
        required: false

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Import secrets as env vars (YAML)
        shell: bash
        run: |
            echo "${{ secrets.GENERIC_YAML_SECRET }}" | yq eval 'to_entries | .[] | .key + ": " + (.value|tostring)' - | while read line; do echo "$line"; done -

      - name: debug
        shell: bash
        run: |
          echo "${{ env.secret_1 }}"
          echo "${{ env.secret_2 }}"
